name: Workflow Test CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev


jobs:
  lint:
    runs-on: ubuntu-latest
    name: Code lint
    steps:
      - name: Docker Image
        uses: LucasVmigotto/workflow-test/actions/main@v1
      - name: Install dependencies
        run: yarn
      - name: Linter
        run: yarn run lint