name: Workflow Test CI

on:
  pull_request:
    branches:
      - master
      - dev


jobs:
  test:
    runs-on: ubuntu-latest
    name: Test code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Image
        uses: LucasVmigotto/workflow-test/docker@master
      - name: Install dependencies
        run: yarn
      - name: Cache modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Test
        run: yarn run test